# GENERATED by vendor.py — do not edit.
# '<key>.<script>': the exact call the script's __main__ makes.
ENTRY = {
    'basestation.build_provenance_html': 'main()',
    'basestation.compute_recommendations': 'main(sys.argv)',
    'basestation.export_results_xlsx': 'main(sys.argv)',
    'basestation.run_pipeline': 'main(sys.argv)',
    'checkpoint.build_provenance_html': 'main()',
    'checkpoint.compute_recommendations': 'main(sys.argv)',
    'checkpoint.export_results_xlsx': 'main()',
    'checkpoint.run_pipeline': 'main()',
    'drone.build_provenance_html': 'main()',
    'drone.compute_recommendations': 'main()',
    'drone.export_results_xlsx': 'main()',
    'drone.run_pipeline': 'main()',
    'gcp.build_provenance_html': 'main()',
    'gcp.compute_recommendations': 'main(sys.argv)',
    'gcp.export_results_xlsx': 'main()',
    'gcp.run_pipeline': 'main()',
}
